### ISSUE TITLE
[Bug] Script errors out in some combinations

### ISSUE THREAD

**Issue by humanascode** [emrgcl/AzureVMPricingCLI#6]
The script errors out in some combinations.
Example:

![image](https://github.com/emrgcl/AzureVMPricingCLI/assets/64002130/9991b335-486c-4161-bb99-50eba8c97dab)

**Comment by emrgcl** [comment]
It's probably that some prices (1 & 3 year saving plans are not available for the selected region) I need to add controls for such. Thanks a lot for testing and pointing out @humanascode 


<img width="1327" alt="image" src="https://github.com/emrgcl/AzureVMPricingCLI/assets/41307814/68b7ca3c-c4ae-4bcf-86d6-2a6093314b35">

**Comment by emrgcl** [comment]
This is due to some regions dont have some skus (like saving plans). They are now set as 0. The issue is solved.

thank you @humanascode  for pointing the bug. i
