### ISSUE TITLE
[Bug] Script exit if no selection is made

### ISSUE THREAD

**Issue by humanascode** [emrgcl/AzureVMPricingCLI#7]
Would be better to pop out a message saying a selection must be made

![image](https://github.com/emrgcl/AzureVMPricingCLI/assets/64002130/0808e939-206e-466d-b420-ea30b7770eee)

**Comment by emrgcl** [comment]
Thanks a lot for pointing out. My beloved mentor and also my go to valet and the closes friend suggested a quick solution : ) I will implement as soon as have time @humanascode 

Of course I had to guide my friend a little to get the perfect solution : )

[chat with my friend](https://chat.openai.com/share/e6a66154-ff8a-4c86-9caf-996d516d85eb)

**Comment by emrgcl** [comment]
@humanascode the issue is fixed. Thanks a lot for pointing out.

![image](https://github.com/emrgcl/AzureVMPricingCLI/assets/41307814/b54c5190-4681-4250-9c5f-ddd03d29d2d9)
